services:

    greeting1:
        container_name: greeting-1
        build:
            context: .
            dockerfile: srv.Dockerfile
        environment:
          - ASPNETCORE_URLS=http://+:8100

    greeting2:
        container_name: greeting-2
        build:
            context: .
            dockerfile: srv.Dockerfile
        environment:
          - ASPNETCORE_URLS=http://+:8200

    load-balancer:
        container_name: ha_proxy
        build:
            context: .
            dockerfile: lb.Dockerfile
        volumes:
          - ./keycloak-data/keys/:/keys/public
        ports:
            - target: 8080
              published: 3000
              protocol: tcp
            - target: 80
              published: 8090
              protocol: tcp
        depends_on:
          - greeting1
          - greeting2
          - oauth_server
          
    database:
        image: postgres:alpine
        container_name: postgres
        ports:
          - 5432:5432
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        volumes:
          - postgres:/var/lib/postgresql/data
          - ./db-init:/docker-entrypoint-initdb.d

# For convinience
    # adminer:
    #   image: adminer
    #   restart: always
    #   ports:
    #     - 8180:8080
    #   depends_on:
    #     - database

    oauth_server:
        image: quay.io/keycloak/keycloak:latest
        command: start --hostname=localhost --http-enabled=true --features=token-exchange,admin --import-realm --proxy-headers forwarded --http-relative-path auth
        volumes:
          - ./keycloak-data/realm:/opt/keycloak/data/import/
        environment:
          - KC_PROXY=edge
          - KEYCLOAK_IMPORT=/opt/keycloak/data/import/devops-test.json
          - KEYCLOAK_ADMIN=admin
          - KEYCLOAK_ADMIN_PASSWORD=admin
          - KC_DB=postgres
          - KC_DB_URL_HOST=database
          - KC_DB_URL_DATABASE=keycloak
          - KC_DB_URL_PORT=5432
          - KC_DB_USERNAME=keycloak
          - KC_DB_PASSWORD=keycloak
        depends_on:
          - database
volumes:
  postgres:
