version: "3.0"
services:
    load-balancer:
        build:
            context: .
            dockerfile: lb.Dockerfile
        ports:
            - target: 8080
              published: 3000
              protocol: tcp

    greeting1:
        build:
            context: .
            dockerfile: srv.Dockerfile
        environment:
          - ASPNETCORE_URLS=http://+:8100

    greeting2:
        build:
            context: .
            dockerfile: srv.Dockerfile
        environment:
          - ASPNETCORE_URLS=http://+:8200
